###
GET http://localhost:3000/api/status

###
GET http://localhost:3000/api/login

###
GET http://localhost:3000/api/register

### Get user info by uuid
GET http://localhost:3000/api/users/4de4ed79-a3c8-4efc-b2bf-498c50ab95b3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDZiNDcwY2YtZDY4MC00Yzg1LWE0NGQtZjdkODQ1MzAzOGM4IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ1NDczMywiZXhwIjoxNjg3NDU0NzYzfQ.bmy8p5IpBuEeXWQCVFmUQf_PvxYT_NZOgtoKOgZVvDg

### get all users
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDZiNDcwY2YtZDY4MC00Yzg1LWE0NGQtZjdkODQ1MzAzOGM4IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ1NDczMywiZXhwIjoxNjg3NDU0NzYzfQ.bmy8p5IpBuEeXWQCVFmUQf_PvxYT_NZOgtoKOgZVvDg

### update user info
POST http://localhost:3000/api/users/4de4ed79-a3c8-4efc-b2bf-498c50ab95b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDZiNDcwY2YtZDY4MC00Yzg1LWE0NGQtZjdkODQ1MzAzOGM4IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ1NDczMywiZXhwIjoxNjg3NDU0NzYzfQ.bmy8p5IpBuEeXWQCVFmUQf_PvxYT_NZOgtoKOgZVvDg

{
  "email":"john@example.com",
  "firstName": "John",
  "lastName": "Doe"
}

### update user info
POST http://localhost:3000/api/users/4de4ed79-a3c8-4efc-b2bf-498c50ab95b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDZiNDcwY2YtZDY4MC00Yzg1LWE0NGQtZjdkODQ1MzAzOGM4IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ1NDczMywiZXhwIjoxNjg3NDU0NzYzfQ.bmy8p5IpBuEeXWQCVFmUQf_PvxYT_NZOgtoKOgZVvDg

{
  "email":"john1@example.com"
}

### update user info
POST http://localhost:3000/api/users/4de4ed79-a3c8-4efc-b2bf-498c50ab95b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDZiNDcwY2YtZDY4MC00Yzg1LWE0NGQtZjdkODQ1MzAzOGM4IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ1NDczMywiZXhwIjoxNjg3NDU0NzYzfQ.bmy8p5IpBuEeXWQCVFmUQf_PvxYT_NZOgtoKOgZVvDg

{

}

###
POST http://localhost:3000/api/users/update-password/4de4ed79-a3c8-4efc-b2bf-498c50ab95b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDZiNDcwY2YtZDY4MC00Yzg1LWE0NGQtZjdkODQ1MzAzOGM4IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ1NDczMywiZXhwIjoxNjg3NDU0NzYzfQ.bmy8p5IpBuEeXWQCVFmUQf_PvxYT_NZOgtoKOgZVvDg

{
  "password": "A!1234",
  "newPassword": "A!12345"
}
### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@example.com",
  "password": "A!12345"
}

### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstName": "admin",
  "lastName": "admin",
  "email": "admin@example.com",
  "password": "Admin!.123321"
}

### 
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "John!1"
}

### 
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin!1"
}
   

###
GET http://localhost:3000/api/refresh/06b470cf-d680-4c85-a44d-f7d8453038c8

###
GET http://localhost:3000/api/logout

